### ISSUE TITLE
No resource specifications for neuron-device-plugin ds

### ISSUE THREAD

**Issue by RobertLucian** [aws/aws-neuron-sdk#103]
The current daemonset for [k8s-neuron-device-plugin.yaml](https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/k8s-neuron-device-plugin.yml) doesn't have any resource requests/limits. I take that setting requests/limits is a good strategy to prevent the container from hogging too many resources. 

I'm thinking of something resembling this:
```yaml
resources:
  requests:
    cpu: 200m
    memory: 500Mi
  limits:
    memory: 500Mi
```

What I'm asking is: do the resource requirements change depending on the number of Inferentia chips available? Or depending on other unknown factors?
