### ISSUE TITLE
Failing to allocate 2Mi HugePages on k8s containerized neuron runtime

### ISSUE THREAD

**Issue by RobertLucian** [aws/aws-neuron-sdk#109]
### Description

@mrnikwaws as I have mentioned in https://github.com/aws/aws-neuron-sdk/issues/108, I'm creating a separate ticket here. 

---

Let's say I have the following k8s spec for my pod which gets scheduled on an Inferentia instance. In this case we'll assume it's an `inf1.xlarge`. The following configuration has been extracted with `kubectl describe pods`:
```yaml
spec:
  containers:
  - image: 680870929100.dkr.ecr.eu-central-1.amazonaws.com/cortexlabs/neuron-rtd:latest
    imagePullPolicy: Always
    name: neuron-rtd
    resources:
      limits:
        aws.amazon.com/infa: "1"
        hugepages-2Mi: "256"
      requests:
        aws.amazon.com/infa: "1"
        hugepages-2Mi: "256"
        memory: "2994757120"
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
        - IPC_LOCK
    volumeMounts:
    - mountPath: /sock
      name: sock
```
```yaml
  - image: 680870929100.dkr.ecr.eu-central-1.amazonaws.com/cortexlabs/python-serve-accelerator:latest
    imagePullPolicy: Always
    name: api
    ports:
    - containerPort: 8888
      protocol: TCP
    resources:
      requests:
        cpu: 2990m
        memory: "2994757120"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /mnt
      name: mnt
    - mountPath: /sock
      name: sock
```

After having configured the instance to use the right value for HugePages, calling
```bash
grep HugePages_Total /proc/meminfo | awk {'print $2'}
```
gets me 128. I get the same thing calling this in the runtime container too, not just on the host.

The `680870929100.dkr.ecr.eu-central-1.amazonaws.com/cortexlabs/neuron-rtd:latest` has been built after [this Dockerfile's](https://github.com/aws/aws-neuron-sdk/blob/94402fabd2887b647028a2a24cb6efc8c87ab5cf/docs/neuron-container-tools/docker-example/Dockerfile.neuron-rtd) blueprint.

### Problem 

When I try launching the runtime in the runtime container with `neuron-rtd -g unix:/sock/neuron.sock -x -l 15`, I get the following error:
```
nrtd[287]: [NRTD:nrtd_main] nrtd build using:1.0.6222.0
nrtd[287]: [NRTD:json_from_file] Read JSON from: /run/infa-map.json
nrtd[287]: [NRTD:json_from_file] Read JSON from: /opt/aws/neuron/config/neuron-rtd.config
nrtd[287]: [NRTD:parse_value] key: copy_intermediate_output does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: debug_flags does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: dma_perf_emulation does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: sb_memset does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: enable_dma_tracing does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: fmap_in_huge_tlb does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: reset_devices does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: use_interrupts does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: enable_shmem_hugetlb does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: drop_all_capabilities does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: num_hugepages_per_mla does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: map_bar4 does not exist in current configuration
nrtd[287]: [NRTD:parse_value] key: readless_read does not exist in current configuration
nrtd[287]: [NRTD:parse_list] key: num_dma does not exist in current configuration
nrtd[287]: [NRTD:set_default_tpb_list] Use default NC map
nrtd[287]: [NRTD:parse_value] key: tpb_init_config does not exist in current configuration
nrtd[287]: [NRTD:nrtd_main] Registering SIGINT
nrtd[287]: [NRTD:InitTongas] Initializing MLA at 0000:00:1f.0
nrtd[287]: [NMGR:kmgr_init_mlas] Init device 0000:00:1f.0
nrtd[287]: [TDRV:kbin_idx_create] allocated 160 bytes 1280 32 40
nrtd[287]: [TDRV:hugetlb_mmap] mlock failed, error -1, check hugetlb cgroup hierarchy limits
nrtd[287]: [TDRV:hugetlb_cache_init] Failed to mmap huge page 1 out of requested 128
nrtd[287]: [TDRV:hugetlb_cache_destroy] Destroying hugetlb
nrtd[287]: [TDRV:tdrv_init] Attempt to preallocate 128 hugetlb pages failed, required 128 pages per device
nrtd[287]: [TDRV:sysfs_unmap_bar] Unmapping sysfs ptr: (nil), size: 0, fd: 0
nrtd[287]: [TDRV:sysfs_unmap_bar] Unmapping sysfs ptr: (nil), size: 0, fd: 0
nrtd[287]: [TDRV:sysfs_unmap_bar] Unmapping sysfs ptr: (nil), size: 0, fd: 0
nrtd[287]: [TDRV:hugetlb_cache_destroy] Destroying hugetlb
nrtd[287]: [TDRV:tdrv_destory] TDRV not initialized
nrtd[287]: [NRTD:InitTongas] Failed to initialize devices, error:4
nrtd[287]: [NRTD:nrtd_main] Failed to initialize devices: 0000:00:1f.0 , attempt: 2
```

Interestingly, this **does work** when I run the command directly onto the host. It starts listening on that socket.

### System verifications

Everything else looks fine to me. Just as I mentioned before, `cat /proc/meminfo` looks fine. The HugePages section of this file is identical on the host and on the running container. I get those 128 2Mi HugePage files.
```
...
HugePages_Total:     128
HugePages_Free:      128
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
...
```

Both for `/sys/devices/system/node/node0/hugepages/hugepages-2048kB/free_hugepages` and `/sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages` I get `128`, which is expected.

Inspecting `/sys/fs/cgroup/hugetlb/kubepods/hugetlb.2MB.limit_in_bytes` with `cat` gets me `268435456`, which is exactly 256Mi, which is good.

For `/sys/fs/cgroup/hugetlb/kubepods/hugetlb.2MB.max_usage_in_bytes` and `sys/fs/cgroup/hugetlb/kubepods/hugetlb.2MB.usage_in_bytes` I get `0`.

Inside the container, the contents of `/opt/aws/neuron/config/neuron-rtd.config` are:
```
{
   "model_params_default" : {
      "ninfer" : 4,
      "io_dma_data_host" : true,
      "io_dma_ring_host" : false,
      "timeout" : 2,
      "validate_nn_package_hash": true
   },
   "init_config" : {
       "shmem_enabled": true,
       "num_hugepages_per_device": 128,
       "share_tdram" : false,
       "pooling_thread_cpu_affinity_start": -1,
       "pooling_thread_sleep_interval": 1,
       "model_cache_count": 0,
       "debug": false,
       "allow_metric" : false,
       "metric_send_interval_secs": 300,
       "enable_node_profiling": false
   }
}
```

The version of the runtime is `1.0.6222.0`. I've also tried version `1.0.5795.0` with the same results.

---

Do you know what is the solution here?

**Comment by mrnikwaws** [comment]
Hi Robert,

The team took a look at this issue today and we believe that you have a typo in your configuration which is causing the issue.  Can you try replacing 

```
    resources:
      limits:
        aws.amazon.com/infa: "1"
        hugepages-2Mi: "256"
      requests:
        aws.amazon.com/infa: "1"
        hugepages-2Mi: "256"
        memory: "2994757120"
```

with

```
    resources:
      limits:
        aws.amazon.com/infa: "1"
        hugepages-2Mi: "256Mi"
      requests:
        aws.amazon.com/infa: "1"
        hugepages-2Mi: "256Mi"
        memory: "2994757120"
```
