### ISSUE TITLE
kubelet.conf file missing. Possible missing steps in tutorial?

### ISSUE THREAD

**Issue by grant-swinton** [aws/aws-neuron-sdk#180]
Attempting to follow the k8 kubernetes guide from here: https://github.com/aws/aws-neuron-sdk/blob/master/docs/neuron-container-tools/tutorial-k8s.md

I'm using Kubernetes 1.15 on an EKS cluster. I appreciate any help you can give me.

There was a problem with the yaml file in the tutorial (unknown Service Account neuron-device-plugin) until I also applied k8s-neuron-device-plugin-rbac.yml, which seems to define it. For completeness I also applied the other 2 .yml files in that repository (k8s-neuron-scheduler-config.yml, k8s-neuron-scheduler.yml). None of these URLs seemed to work, so I ended up copying all the files to a local directory before applying them.

The neuron plugin daemonset then starts crash loop backoff. Looking at the logs gives

```
2020/10/12 20:43:28 kubeconfig /etc/kubernetes/kubelet.conf failed to find due to stat /etc/kubernetes/kubelet.conf: no such file or directory
neuron-device-plugin: 2020/10/12 20:43:28 Fetching devices.
neuron-device-plugin: 2020/10/12 20:43:28 Error to get IB device: open /run/infa-map.json: no such file or directory
neuron-device-plugin: 2020/10/12 20:43:28 No devices found.
neuron-device-plugin: 2020/10/12 20:43:28 Device list: []
neuron-device-plugin: 2020/10/12 20:43:28 Starting FS watcher.
neuron-device-plugin: 2020/10/12 20:43:28 Starting OS watcher.
neuron-device-plugin: 2020/10/12 20:43:28 Error to get devices: open /run/infa-map.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11a8b66]

goroutine 1 [running]:
main.(*DevicePlugin).cleanup(0x0, 0x1, 0x1)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/server.go:300 +0x26
main.(*DevicePlugin).Start(0x0, 0xc00014bab8, 0x10)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/server.go:85 +0x2f
main.(*DevicePlugin).Serve(0x0, 0x1441aed, 0x15, 0xc0002a9da0, 0x0)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/server.go:326 +0x35
main.main()
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/main.go:64 +0x3a8
```

I can see where both /run and /etc/kubernetes/kublet.conf are described as volumes, but don't see those files in the container or any reference to them in the tutorial (or the preceding docker tutorial). What are they supposed to be and how should they be put in the appropriate position? 

I'm not entirely sure what else might be relevant so I have included some additional code used in this project.

terraform code to generate inf1 instance

```
worker_groups_launch_template: [{
      name                      = "worker-group-inf1-v-1-17"
      instance_type             = "inf1.xlarge"
      override_instance_types   = ["inf1.xlarge"]
      spot_instance_pools       = 1
      spot_allocation_strategy  = "lowest-price"
      spot_max_price            = "0.4"
      ami_id                    = "ami-000c56e8536aaaf50"
      pre_userdata              = ""
      additional_userdata       = "sudo mkdir -p /opt/models/model-store && sudo aws s3 cp s3://airpr-dataprovider/models/neuron-archive/ner/ner_neuron_b6.mar /opt/models/model-store && sudo aws s3 cp s3://airpr-dataprovider/models/neuron-archive/setup-neuronrtd.sh /opt/models/model-store && exec /opt/models/model-store/setup-neuronrtd.sh"
      asg_desired_capacity      = 1
      asg_max_size              = 1
      asg_min_size              = 1
      kubelet_extra_args        = "--node-labels=kubernetes.io/lifecycle=spot,workertype=inf1"
      key_name                  = var.key
      iam_instance_profile_name = var.worker_iam_role_name
      tags = [
        {
          "key"                 = "k8s.io/cluster-autoscaler/enabled"
          "propagate_at_launch" = "false"
          "value"               = "true"
        },
        {
          "key"                 = "k8s.io/cluster-autoscaler/${var.cluster_name}"
          "propagate_at_launch" = "false"
          "value"               = "true"
        }
      ]
    }]
```

In case it matters, the kubernetes for the application that is supposed to ultimately use neuron. 

```
apiVersion: v1
kind: Service
metadata:
  name: ner-inf
  labels:
    app: ner-inf-v1
spec:
  selector:
    app: ner-inf-v1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner-inf-v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: ner-inf-v1
  template:
    metadata:
      labels:
        app: ner-inf-v1
    spec:
      volumes:
        - name: sock
          emptyDir: {}
        - name: model-file
          hostPath:
            path: /opt/models/model-store
            type: Directory
      nodeSelector:
        workertype: inf1
      containers:
        - name: ner-inf
          image: 484375727565.dkr.ecr.us-east-1.amazonaws.com/serve-ner:v1
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          command:
            - serve
          #args:

          #inferentia setup
          env:
            - name: NEURON_RTD_ADDRESS
              value: unix:/sock/neuron.sock
          volumeMounts:
            - name: model-file
              mountPath: "/home/model-server/model-store"
            - name: sock
              mountPath: /sock

        - name: neuron-rtd
          image: 790709498068.dkr.ecr.us-east-1.amazonaws.com/neuron-rtd:latest # neuron-rtd image.
          imagePullPolicy: IfNotPresent

          # Neuron-rtd required capabilities
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - IPC_LOCK
          #env:
          #  - name: AWS_NEURON_VISIBLE_DEVICES
          #    value: "0"
          # Shared volume mount, for UDS socket
          volumeMounts:
            - name: sock
              mountPath: /sock

          resources:
            limits:
              hugepages-2Mi: 256Mi    # configure to 256 * desired number of Inferentia devices.
              aws.amazon.com/neuron: 1  # desired number of Inferentia devices.
            requests:
              memory: 1024Mi 
```
