### ISSUE TITLE
Neuron plugin daemonset pods failing with runtime error

### ISSUE THREAD

**Issue by gaurav34065** [aws/aws-neuron-sdk#312]
- Launched `inf1.xlarge` instance type nodes in k8s cluster with  below ansible steps over the node
- Followed [this](https://awsdocs-neuron.readthedocs-hosted.com/en/v1.12.0/neuron-deploy/tutorial-k8s.html) doc to create daemonset.

```
- name: aws neuron gpg key
  rpm_key:
    state: present
    key: https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB

- name: get machine kernel release
  shell: "uname -r"
  register: pl_kernel_release

- name: install dependencies for neuron
  yum: name={{item}} state=present enablerepo=neuron
  when: pl_kernel_release.changed == true
  with_items:
    - kernel-devel-{{pl_kernel_release.stdout | default('4.14.209-160.339.amzn2.x86_64') }}
    - kernel-headers-{{pl_kernel_release.stdout | default('4.14.209-160.339.amzn2.x86_64') }}
    - aws-neuron-dkms
    - aws-neuron-runtime-base
    - aws-neuron-runtime
    - aws-neuron-tools
```
    
**Expected** :  Neuron daemonset pods to come up and i should be able to see resource `aws.amazon.com/neuron: 1` in node description

**Result** : Neuron pods gives error saying below
```
2021/08/17 13:53:21 kubeconfig /etc/kubernetes/kubelet.conf failed to find due to stat /etc/kubernetes/kubelet.conf: no such file or directory
2021/08/17 13:53:21 Device Plugin is in Driver Mode:false
neuron-device-plugin: 2021/08/17 13:53:21 Fetching devices.
neuron-device-plugin: 2021/08/17 13:53:21 Device list: [{0000:00:1f.0 0}]
neuron-device-plugin: 2021/08/17 13:53:21 Starting FS watcher.
neuron-device-plugin: 2021/08/17 13:53:21 Starting OS watcher.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11a9216]

goroutine 1 [running]:
main.(*DevicePlugin).cleanup(0x0, 0x1, 0xc000326088)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/server.go:328 +0x26
main.(*DevicePlugin).Start(0x0, 0x22b32b0, 0xc00016c010)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/server.go:97 +0x2f
main.(*DevicePlugin).Serve(0x0, 0x144255b, 0x15, 0xc0002c9e00, 0x0)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/server.go:354 +0x35
main.main()
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-device-plugin/main.go:64 +0x3a8
```
System Info :
- k8s version 1.18.1
- docker version 18.06.1-ce
